title: Lee Siwoo
description: Web developer
site_title: '@Shu-webbb - Lee Siwoo'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SHU-Webbb
email: siusi0201@gmail.com

# absolute or relative
profile_picture: assets/images/pp.gif

# Google Analytics ID
google_analytics: 
