title: Lee Siwoo
description: Web Developer
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SHU-Webbb
blog_url: 
email: siusi0201@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.gif

# Google Analytics ID
google_analytics: 
